// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://exqyvhpuypjxlgkiqxtq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4cXl2aHB1eXBqeGxna2lxeHRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk3NTEyMDMsImV4cCI6MjA3NTMyNzIwM30.DAj8d-JeFRBL-h-XayMIob9aHy7zFEpqXdcNZesAvJs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});